### ISSUE TITLE
Message for Lynn

### ISSUE THREAD

**Issue by ghost** [lynn/GMSD#2]
Welp, in case of, i'll open an issue too.
I would like to contact you. I made a pull request with my message in it ^^

**Comment by TimeCrusher** [comment]
Ok i'm really a noob to this github thing, but i know a guy who's also working on a GM:S decompiler and he already made a 0,21 public version it works pretty well, so maybe you'll be interested if he can help you and you can help him. I don't know how this works but message me or something i have no idea how this works xD

**Comment by shakvaal** [comment]
@TimeCrusher   What is this "public version" of a GM:S decompiler you are talking about? Even thoroughful googling reveals only [GM 8.x decompiler](http://game-maker.ru/news.php?readmore=133) and [another one](http://game-maker.ru/infusions/pro_download_panel/download.php?did=1087) for GM versions 5, 6 and 7.
Sadly enough, you can't even have the source for the first one without paying codeforge for it. Augh!

**Comment by TimeCrusher** [comment]
https://www.reddit.com/r/Underminers/comments/3yq0v7/flowey_the_decompiler_02_preliminary_script/

**Comment by TimeCrusher** [comment]
@shakvaal https://www.reddit.com/r/Underminers/comments/3yq0v7/flowey_the_decompiler_02_preliminary_script/

**Comment by shakvaal** [comment]
@TimeCrusher  Thank you.
It would be funny if Toby is the very person to stimulate the development and release of the first working GM:S decompiler. He truly is an influence in game industry ^^

**Comment by lynn** [comment]
Bonjour, @nanoplink! I saw your pull request, but I think right here is a good place for communication. (Je suis flamande, et je trouve un peux difficile de communiquer en français! I prefer English.)

I only just recently got a break from exams, and, well, what do you know: Undertale updated its bytecode version, rendering both GMSD and rawr.ws both totally outdated! So until I figure the changes out myself, I can't help you directly -- but if you look around a bit on [Underminers](https://www.reddit.com/r/underminers), you can already find some info about the new changes.
