### ISSUE TITLE
Error: OutOfMemoryException.

### ISSUE THREAD

**Issue by wirehack7** [lynn/GMSD#5]
When I try to run it against a `data.win` file I get:

```OutOfMemoryException.```

My system has 16GB of RAM.

**Comment by lynn** [comment]
Hi @wirehack7! I sort of lost interest in this little project, and soon after I stopped working on it, the `data.win` file format changed, so it’s currently broken. (Presumably, it’s reading the wrong bytes from the file where it expected a size, now, and ends up thinking it needs to allocate a ton of memory, and crashing.)

I recommend you try [Altar.NET](https://gitlab.com/PoroCYon/Altar.NET) instead.
